---
- name: Install HTTP server ubuntu
  hosts: n4
  become: yes

  tasks:
  - name: Install Apache2
    apt:
      name: apache2
      state: latest
      update_cache: true

  - name: Start Apache2
    service:
      name: apache2
      state: started

  - name: Enable Apache2
    service:
      name: apache2
      enabled: yes
...
